FROM python:3.8.6-buster

USER root

RUN apt-get update
RUN apt-get install bash \
                    openssl

RUN groupadd --gid {{ user.gid }} {{ user.group }}
RUN useradd {{ user.name }} -m --uid {{ user.uid }} -g {{ user.group }} -p $(openssl passwd -crypt {{ user.password }}) -s /bin/bash

WORKDIR {{ dir.python_app }}

COPY .{{ dir.python_app }}/requirements.txt .

USER {{ user.name }}

RUN pip install virtualenv
RUN python -m virtualenv {{ user.home }}/venv
RUN . {{ user.home }}/venv/bin/activate && pip install gunicorn
RUN . {{ user.home }}/venv/bin/activate && pip install -r requirements.txt

EXPOSE 9000

USER {{ user.name }}

CMD ["{{ user.home }}/venv/bin/gunicorn", "-b", "0.0.0.0:9000", "-w", "3", "{{ app_names.python_app }}.wsgi:application"]